### ISSUE TITLE
Starting gui fails on Windows 10

### ISSUE THREAD

**Issue by mrx23dot** [semuconsulting/PyGPSClient#128]
λ pip freeze | grep gps
pygpsclient==1.3.26
pynmeagps==1.0.23

```
  λ pygpsclient
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pygpsclient.exe\__main__.py", line 4, in <module>
  File "C:\Python37\lib\site-packages\pygpsclient\__main__.py", line 16, in <module>
    from pygpsclient.app import App
  File "C:\Python37\lib\site-packages\pygpsclient\app.py", line 17, in <module>
    from pygnssutils import GNSSMQTTClient, GNSSNTRIPClient
  File "C:\Python37\lib\site-packages\pygnssutils\__init__.py", line 13, in <module>
    from pygnssutils.gnssmqttclient import GNSSMQTTClient
  File "C:\Python37\lib\site-packages\pygnssutils\gnssmqttclient.py", line 34, in <module>
    import paho.mqtt.client as mqtt
  File "C:\Python37\lib\site-packages\paho\mqtt\client.py", line 116, in <module>
    import dns.resolver
  File "C:\Python37\lib\site-packages\dns\resolver.py", line 38, in <module>
    import dns.query
  File "C:\Python37\lib\site-packages\dns\query.py", line 43, in <module>
    from requests_toolbelt.adapters.source import SourceAddressAdapter
  File "C:\Python37\lib\site-packages\requests_toolbelt\__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "C:\Python37\lib\site-packages\requests_toolbelt\adapters\__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "C:\Python37\lib\site-packages\requests_toolbelt\adapters\ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "C:\Python37\lib\site-packages\requests_toolbelt\_compat.py", line 56, in <module>
    from requests.packages.urllib3.contrib.pyopenssl \
  File "C:\Python37\lib\site-packages\urllib3\contrib\pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "C:\Python37\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Python37\lib\site-packages\OpenSSL\crypto.py", line 1579, in <module>
    class X509StoreFlags(object):
  File "C:\Python37\lib\site-packages\OpenSSL\crypto.py", line 1598, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Comment by semuadmin** [comment]
Hi @mrx23dot, 

Please note that Python 3.7 has been end-of-life since 2023-06-27 and is no longer supported. I strongly recommend you update to a more recent version of Python from the official repository at https://www.python.org/.

Having said that, it's possible that this error may be due to some other obsolete or outdated libraries on your platform (e.g. OpenSSL or cryptography). What version of OpenSSL and the Python cryptography library are you using? If it's not the latest available, I recommend updating (_latest available at time of writing is 42.0.5_):

```sh
python3 -m pip show cryptography
```

```sh
python3 -m pip install --ugprade cryptography
```

A quick Google search on this error messages gives the following, for example:

https://stackoverflow.com/questions/74705127/how-to-fix-error-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check
