### ISSUE TITLE
Unable to start the Tk on Mac m1

### ISSUE THREAD

**Issue by Lynn1996** [semuconsulting/PyGPSClient#62]
Sorry sir, I just followed the guideline and try to run the pygpsclient. I type in `python3 -m pygpsclient` The console gives error: 
```
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/frank/PyGPSClient-master/src/pygpsclient/__main__.py", line 49, in <module>
    main()
  File "/Users/frank/PyGPSClient-master/src/pygpsclient/__main__.py", line 43, in main
    App(root, **kwargs)
  File "/Users/frank/PyGPSClient-master/src/pygpsclient/app.py", line 135, in __init__
    self.__master.iconphoto(True, PhotoImage(file=ICON_APP))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Users/frank/PyGPSClient-master/src/pygpsclient/resources/iconmonstr-location-27-32.png"
```
My python3 version is 3.9.6, and Tk is 8.5. I installed pillow by brew.

**Comment by Lynn1996** [comment]
Dear [semuadmin](https://github.com/semuadmin)，

Amazing! I am using Mac M1 Pro and installed the latest Python version. Everything works now!

Many thanks!
